name: 3DCyclegan
channels:
- pytorch
- defaults
dependencies:
- python=3.10.4
- pytorch=2.0.1
- scipy
- pip
- pip:
  - dominate==2.8.0
  - torchvision==0.15.2
  - Pillow==9.0.1
  - numpy==1.22.3
  - visdom==0.1.8
  - wandb==0.15.8
  - tifffile==2023.7.18
  - pytorch-fid==0.3.0
